In [8]:
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from apyori import apriori
df=pd.read_csv(r"C:\Users\Madhuma k\Downloads\archive (25)\online_retail.csv")
df.head()

ModuleNotFoundError: No module named 'apyori'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [ ]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
df=df.dropna(subset=['Description'])

In [ ]:
df['CustomerID'].fillna('Unknown',inplace=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
le=LabelEncoder()
column_to_convert=['Description','Country']
for col in column_to_convert:
    df[col]=le.fit_transform(df[col])
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,3918,6,2010-12-01 08:26:00,2.55,17850.0,36
1,536365,71053,3926,6,2010-12-01 08:26:00,3.39,17850.0,36
2,536365,84406B,913,8,2010-12-01 08:26:00,2.75,17850.0,36
3,536365,84029G,1910,6,2010-12-01 08:26:00,3.39,17850.0,36
4,536365,84029E,2911,6,2010-12-01 08:26:00,3.39,17850.0,36
5,536365,22752,3158,2,2010-12-01 08:26:00,7.65,17850.0,36
6,536365,21730,1529,6,2010-12-01 08:26:00,4.25,17850.0,36
7,536366,22633,1653,6,2010-12-01 08:28:00,1.85,17850.0,36
8,536366,22632,1650,6,2010-12-01 08:28:00,1.85,17850.0,36
9,536367,84879,244,32,2010-12-01 08:34:00,1.69,13047.0,36

In [ ]:
#records=[]
#for i in range(0,541909):
    #records.append([str(df.values[i,j])for j in range (0,8)])

records=df.iloc[:,0:8].astype(str).values.tolist()
association_rules=apriori(records,min_support=0.0045,min_confidence=0.2,min_lift=3,min_length=2)
association_rules=list(association_rules)
print(association_rules[0])
association_result=list(association_rules)

RelationRecord(items=frozenset({'0.42', '25'}), support=0.008993118293232086, ordered_statistics=[OrderedStatistic(items_base=frozenset({'25'}), items_add=frozenset({'0.42'}), confidence=0.7444702242846095, lift=16.41186250048224)])

In [ ]:
for item in association_rules:
    pair=item[0]
    items=[x for x in pair]
    print("Rule:"+items[0]+"->"+items[1])
    print("Support:"+str(item[1]))

Rule:0.42->25
Support:0.008993118293232086
Rule:0.55->24
Support:0.005685863072159824
Rule:1.63->Unknown
Support:0.02247251895131982
Rule:1.65->10
Support:0.013152412147529742
Rule:Unknown->1.66
Support:0.00465257937879657
Rule:14911.0->10
Support:0.011020447058691634
Rule:2.08->10
Support:0.010360864520251799
Rule:10.79->Unknown
Support:0.005528908587091989
Rule:2->7.95
Support:0.006685513661579971
Rule:2->8.5
Support:0.00504496559146616
Rule:2.46->Unknown
Support:0.03004744136161753
Rule:2.51->Unknown
Support:0.005061782143437714
Rule:2.55->6
Support:0.0071787991860788845
Rule:2.95->6
Support:0.017300494967179697
Rule:4.95->3
Support:0.008015889773107344
Rule:Unknown->3.29
Support:0.019989274776853697
Rule:3.75->4
Support:0.010736434180949836
Rule:Unknown->4.13
Support:0.02765949098165688
Rule:4.96->Unknown
Support:0.008176581269724413
Rule:5.79->Unknown
Support:0.012119128454166487
Rule:7.46->Unknown
Support:0.0057419182453983374
Rule:8.29->Unknown
Support:0.008606337597886347
Rule:36->0.42
Support:0.007683295745225501
Rule:1->0.83
Support:0.010018927963496871
Rule:1->1.63
Support:0.0111587164860133
Rule:1->2.46
Support:0.016575514726628264
Rule:1->Unknown
Support:0.01156418223910521
Rule:1->Unknown
Support:0.015910326670864575
Rule:1->4.96
Support:0.004889879612172941
Rule:1->5.79
Support:0.007918727472827255
Rule:1->8.29
Support:0.005775551349341445
Rule:2->1.63
Support:0.004613340757529611
Rule:36->1.63
Support:0.02247251895131982
Rule:1.65->36
Support:0.010530898545741955
Rule:36->Unknown
Support:0.00465257937879657
Rule:36->2.08
Support:0.008862322889008888
Rule:36->10.79
Support:0.005528908587091989
Rule:2->2.46
Support:0.005697074106807527
Rule:2->36
Support:0.0057363127280744865
Rule:2->Unknown
Support:0.005323372951884108
Rule:36->2.46
Support:0.03004744136161753
Rule:36->2.51
Support:0.005061782143437714
Rule:36->2.55
Support:0.005633544910470546
Rule:36->2.95
Support:0.014056768942444417
Rule:36->Unknown
Support:0.019989274776853697
Rule:36->3.75
Support:0.008925852085345869
Rule:36->Unknown
Support:0.02765949098165688
Rule:36->4.96
Support:0.008176581269724413
Rule:36->5.79
Support:0.012119128454166487
Rule:36->7.46
Support:0.0057419182453983374
Rule:36->8.29
Support:0.008606337597886347
Rule:1->0.83
Support:0.010018927963496871
Rule:1->1.63
Support:0.0111587164860133
Rule:1->36
Support:0.016575514726628264
Rule:1->36
Support:0.01156418223910521
Rule:1->36
Support:0.015910326670864575
Rule:1->4.96
Support:0.004889879612172941
Rule:1->5.79
Support:0.007918727472827255
Rule:1->8.29
Support:0.005775551349341445
Rule:2->1.63
Support:0.004613340757529611
Rule:2->36
Support:0.005697074106807527
Rule:2->36
Support:0.005323372951884108

In [ ]:
print("Confidence:"+str(item[2][0][2]))
print("Lift:"+str(item[2][0][3]))

Confidence:0.9677309782608695
Lift:3.919456932514757